### ISSUE TITLE
Running the mlm on M1 macs

### ISSUE THREAD

**Issue by MarkLTurner** [DurhamARC/classroom-abm#34]
From within the conda environment, python3 invokes /opt/homebrew/Caskroom/miniconda/base/envs/classroom_abm/bin/python3 which is python version 3.7.9. This fails with the following error:

```
(classroom_abm) classroom-abm/multilevel_analysis (mlm) $ python3 multilevel_analysis.py ~/Applications/mln-files     
Traceback (most recent call last):
  File "multilevel_analysis.py", line 6, in <module>
    import rpy2.robjects as ro
  File "/opt/homebrew/Caskroom/miniconda/base/envs/classroom_abm/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "/opt/homebrew/Caskroom/miniconda/base/envs/classroom_abm/lib/python3.7/site-packages/rpy2/rinterface.py", line 12, in <module>
    from rpy2.rinterface_lib import openrlib
  File "/opt/homebrew/Caskroom/miniconda/base/envs/classroom_abm/lib/python3.7/site-packages/rpy2/rinterface_lib/openrlib.py", line 44, in <module>
    rlib = _dlopen_rlib(R_HOME)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/classroom_abm/lib/python3.7/site-packages/rpy2/rinterface_lib/openrlib.py", line 37, in _dlopen_rlib
    rlib = ffi.dlopen(lib_path)
OSError: cannot load library '/opt/homebrew/Cellar/r/4.0.5/lib/R/lib/libR.dylib': dlopen(/opt/homebrew/Cellar/r/4.0.5/lib/R/lib/libR.dylib, 2): no suitable image found.  Did find:
	/opt/homebrew/Cellar/r/4.0.5/lib/R/lib/libR.dylib: mach-o, but wrong architecture
	/opt/homebrew/Cellar/r/4.0.5/lib/R/lib/libR.dylib: mach-o, but wrong architecture
```

Interestingly, when I call a brew installed version of python 3.9.2 with the following command it succeeds both inside and outside the conda environment:
```
/opt/homebrew/bin/python3 multilevel_analysis.py ~/Applications/mln-files
```

**Comment by alisonrclarke** [comment]
Can we close this now @MarkLTurner (following #38)?

**Comment by MarkLTurner** [comment]
Thanks, yes the new multilevel model works nicely.
